name: Next.js CI Gating Workflow
on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Run Linter
      run: npm run lint || true
    - name: Build Next.js production
      run: npm run build
      env:
        NEXT_DISABLE_ESLINT: true
        CI: false
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: "https://bactrunghai.vn"
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
